### ISSUE TITLE
プレイリストを再生できない

### ISSUE THREAD

**Issue by nideka** [Cosgy-Dev/JMusicBot-JP#26]
プレイリストを作成し再生しようとすると再生されない。
[04:52:10] [ERROR] [JDA]: One of the EventListeners had an uncaught exception
java.lang.RuntimeException: java.lang.StackOverflowError
        at com.jagrosh.jdautilities.command.CommandListener.onCommandException(CommandListener.java:118)
        at com.jagrosh.jdautilities.command.Command.run(Command.java:276)
        at com.jagrosh.jdautilities.command.Command.run(Command.java:180)
        at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:498)
        at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onEvent(CommandClientImpl.java:398)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.StackOverflowError: null
        at java.base/sun.nio.fs.UnixNativeDispatcher.mkdir0(Native Method)
        at java.base/sun.nio.fs.UnixNativeDispatcher.mkdir(UnixNativeDispatcher.java:226)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.createGuildFolder(PlaylistLoader.java:56)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:44)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)
        at com.jagrosh.jmusicbot.playlist.PlaylistLoader.getPlaylistNames(PlaylistLoader.java:45)

!!Playlistsでは
「このサーバーの再生リストフォルダが存在しないため作成できませんでした。」が表示されます。
[04:39:32] [DEBUG] [Requester]: Received response with following cf-rays: [60b1cbf7ea7afbdc-KIX]
[04:39:42] [DEBUG] [Requester]: Received response with following cf-rays: [60b1cc397d39fcd1-KIX]

playlistsfolderは標準のPlaylists及び絶対パスでも同じ現象が出ます。
OS:Ubuntu Server 20.04 
BotVersion 0.5.2
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

**Comment by kosugikun** [comment]
ボットのjarファイルと同じフォルダ階層に'Playlists'フォルダはありますか？

**Comment by nideka** [comment]
もちろん同一階層にあります。
-rwxr-xr-x 1 root root 32889422 Nov  7 13:15 JMusicBot-0.5.1.jar*
-rwxr-xr-x 1 root root 32893868 Jan  2 03:58 JMusicBot-0.5.2.jar*
drwxr-xr-x 2 root root        0 Jan  2 04:08 Music/
drwxr-xr-x 2 root root        0 Jan 14  2020 Playlists/
-rwxr-xr-x 1 root root    10746 Jan  2 14:21 config.txt*
drwxr-xr-x 2 root root        0 Jan  1 17:36 logs/

**Comment by tom98delta** [comment]
playlist append＜ファイルネーム＞で保存したプレイリストの文字コードがANSIになってしまいます。
notepadで名前を付けて保存→文字コードをUTF-8にすると再生は出来ますが、ほかのユーザーがコマンドで作ったリストはANSIになった時点で再生が出来ません。
UTF-8で保存できませんでしょうか？

**Comment by kosugikun** [comment]
最新バージョンで強制的にUTF-8を使用するように修正しました。
