### ISSUE TITLE
searchコマンドが使用できません

### ISSUE THREAD

**Issue by favnue** [Cosgy-Dev/JMusicBot-JP#37]
バージョン0.6.1ではsearchが正常に機能しますが、バージョン 0.6.2 ~ 0.6.7β2 では機能しません

<details>
<summary>使用環境</summary>

環境➀
Windows 11 Pro
OS ビルド    22000.556
Java8 ver.321 x86_64

環境②
Windows 10 Home
OS ビルド     19044.1586
Java8 ver.321 x86_64
</details>

<details>
<summary>エラーログ</summary>
[01:22:16] [ERROR] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
	at com.jagrosh.jdautilities.menu.OrderedMenu.initialize(OrderedMenu.java:155)
	at com.jagrosh.jdautilities.menu.OrderedMenu.display(OrderedMenu.java:147)
	at dev.cosgy.JMusicBot.slashcommands.music.SearchCmd$ResultHandler.playlistLoaded(SearchCmd.java:207)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:446)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</details>

**Comment by kosugikun** [comment]
報告ありがとうございます。
[6abcc5d](https://github.com/Cosgy-Dev/JMusicBot-JP/commit/6abcc5d067cc940aaf0efbd416829557b327130d)
0.6.7β4で修正が完了しました。ご協力ありがとうございました。
