### ISSUE TITLE
謎のエラーが常に出されている

### ISSUE THREAD

**Issue by aic-6301** [Cosgy-Dev/JMusicBot-JP#42]
09:25:32] [ERROR] [GensokyoInfoAgent]: 情報を取得中に例外が発生しました！
org.json.JSONException: Mismatched input and form at 9368 [character 6 line 130]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.XML.parse(XML.java:314)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.parse(XML.java:381)
	at org.json.XML.toJSONObject(XML.java:520)
	at org.json.XML.toJSONObject(XML.java:548)
	at org.json.XML.toJSONObject(XML.java:472)
	at dev.cosgy.agent.GensokyoInfoAgent.fetch(GensokyoInfoAgent.java:42)
	at dev.cosgy.agent.GensokyoInfoAgent.run(GensokyoInfoAgent.java:69)
というエラーがずっと出されているのですが私だけでしょうか🤔

**Comment by Kakuzatou** [comment]
私も同じエラーが表示されます。

**Comment by kosugikun** [comment]
この不具合はバージョン0.7.0で修正されました。
